name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # executa diariamente à meia-noite UTC
  workflow_dispatch:      # permite executar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Ronaldo251
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to GitHub
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add dist
          git commit -m "gerando cobrinha animada 🐍" || echo "nada para commit"
          git push
